BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Activo ADD
	TraBaj_Codigo int NULL
GO

/*
ALTER TABLE dbo.Activo
ADD FOREIGN KEY (TraBaj_Codigo) REFERENCES TransaccionBaja(TraBaj_Codigo)
GO*/

ALTER TABLE dbo.Activo SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
