//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activo", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Activo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Activo_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_CodigoAuxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_CodigoBarraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Activo_FechaBajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Activo_FechaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Activo_FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Activo_FechaUsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_ResponsableMantenimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activo_SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebInventario.ServiceReference1.Caracteristica[] CaracteristicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Entida_CustodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Entida_ProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Factura_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_CentroCostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_ClaseActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_EstadoActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_EstadoDepreciacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_TipoBajaActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_CentroCostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_ClaseActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_EstadoActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_EstadoDepreciacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_TipoBajaActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool esNuevoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Activo_Codigo {
            get {
                return this.Activo_CodigoField;
            }
            set {
                if ((this.Activo_CodigoField.Equals(value) != true)) {
                    this.Activo_CodigoField = value;
                    this.RaisePropertyChanged("Activo_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_CodigoAux {
            get {
                return this.Activo_CodigoAuxField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_CodigoAuxField, value) != true)) {
                    this.Activo_CodigoAuxField = value;
                    this.RaisePropertyChanged("Activo_CodigoAux");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_CodigoBarra {
            get {
                return this.Activo_CodigoBarraField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_CodigoBarraField, value) != true)) {
                    this.Activo_CodigoBarraField = value;
                    this.RaisePropertyChanged("Activo_CodigoBarra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_Descripcion {
            get {
                return this.Activo_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_DescripcionField, value) != true)) {
                    this.Activo_DescripcionField = value;
                    this.RaisePropertyChanged("Activo_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Activo_FechaBaja {
            get {
                return this.Activo_FechaBajaField;
            }
            set {
                if ((this.Activo_FechaBajaField.Equals(value) != true)) {
                    this.Activo_FechaBajaField = value;
                    this.RaisePropertyChanged("Activo_FechaBaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Activo_FechaCompra {
            get {
                return this.Activo_FechaCompraField;
            }
            set {
                if ((this.Activo_FechaCompraField.Equals(value) != true)) {
                    this.Activo_FechaCompraField = value;
                    this.RaisePropertyChanged("Activo_FechaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Activo_FechaIngreso {
            get {
                return this.Activo_FechaIngresoField;
            }
            set {
                if ((this.Activo_FechaIngresoField.Equals(value) != true)) {
                    this.Activo_FechaIngresoField = value;
                    this.RaisePropertyChanged("Activo_FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Activo_FechaUso {
            get {
                return this.Activo_FechaUsoField;
            }
            set {
                if ((this.Activo_FechaUsoField.Equals(value) != true)) {
                    this.Activo_FechaUsoField = value;
                    this.RaisePropertyChanged("Activo_FechaUso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_Modelo {
            get {
                return this.Activo_ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_ModeloField, value) != true)) {
                    this.Activo_ModeloField = value;
                    this.RaisePropertyChanged("Activo_Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_Observacion {
            get {
                return this.Activo_ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_ObservacionField, value) != true)) {
                    this.Activo_ObservacionField = value;
                    this.RaisePropertyChanged("Activo_Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_ResponsableMantenimiento {
            get {
                return this.Activo_ResponsableMantenimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_ResponsableMantenimientoField, value) != true)) {
                    this.Activo_ResponsableMantenimientoField = value;
                    this.RaisePropertyChanged("Activo_ResponsableMantenimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo_Serie {
            get {
                return this.Activo_SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.Activo_SerieField, value) != true)) {
                    this.Activo_SerieField = value;
                    this.RaisePropertyChanged("Activo_Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebInventario.ServiceReference1.Caracteristica[] Caracteristicas {
            get {
                return this.CaracteristicasField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristicasField, value) != true)) {
                    this.CaracteristicasField = value;
                    this.RaisePropertyChanged("Caracteristicas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Entida_Custodio {
            get {
                return this.Entida_CustodioField;
            }
            set {
                if ((this.Entida_CustodioField.Equals(value) != true)) {
                    this.Entida_CustodioField = value;
                    this.RaisePropertyChanged("Entida_Custodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Entida_Proveedor {
            get {
                return this.Entida_ProveedorField;
            }
            set {
                if ((this.Entida_ProveedorField.Equals(value) != true)) {
                    this.Entida_ProveedorField = value;
                    this.RaisePropertyChanged("Entida_Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Factura_Codigo {
            get {
                return this.Factura_CodigoField;
            }
            set {
                if ((this.Factura_CodigoField.Equals(value) != true)) {
                    this.Factura_CodigoField = value;
                    this.RaisePropertyChanged("Factura_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_CentroCosto {
            get {
                return this.Parame_CentroCostoField;
            }
            set {
                if ((this.Parame_CentroCostoField.Equals(value) != true)) {
                    this.Parame_CentroCostoField = value;
                    this.RaisePropertyChanged("Parame_CentroCosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_ClaseActivo {
            get {
                return this.Parame_ClaseActivoField;
            }
            set {
                if ((this.Parame_ClaseActivoField.Equals(value) != true)) {
                    this.Parame_ClaseActivoField = value;
                    this.RaisePropertyChanged("Parame_ClaseActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_EstadoActivo {
            get {
                return this.Parame_EstadoActivoField;
            }
            set {
                if ((this.Parame_EstadoActivoField.Equals(value) != true)) {
                    this.Parame_EstadoActivoField = value;
                    this.RaisePropertyChanged("Parame_EstadoActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_EstadoDepreciacion {
            get {
                return this.Parame_EstadoDepreciacionField;
            }
            set {
                if ((this.Parame_EstadoDepreciacionField.Equals(value) != true)) {
                    this.Parame_EstadoDepreciacionField = value;
                    this.RaisePropertyChanged("Parame_EstadoDepreciacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_Marca {
            get {
                return this.Parame_MarcaField;
            }
            set {
                if ((this.Parame_MarcaField.Equals(value) != true)) {
                    this.Parame_MarcaField = value;
                    this.RaisePropertyChanged("Parame_Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_TipoBajaActivo {
            get {
                return this.Parame_TipoBajaActivoField;
            }
            set {
                if ((this.Parame_TipoBajaActivoField.Equals(value) != true)) {
                    this.Parame_TipoBajaActivoField = value;
                    this.RaisePropertyChanged("Parame_TipoBajaActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_CentroCosto {
            get {
                return this.Pardet_CentroCostoField;
            }
            set {
                if ((this.Pardet_CentroCostoField.Equals(value) != true)) {
                    this.Pardet_CentroCostoField = value;
                    this.RaisePropertyChanged("Pardet_CentroCosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_ClaseActivo {
            get {
                return this.Pardet_ClaseActivoField;
            }
            set {
                if ((this.Pardet_ClaseActivoField.Equals(value) != true)) {
                    this.Pardet_ClaseActivoField = value;
                    this.RaisePropertyChanged("Pardet_ClaseActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_EstadoActivo {
            get {
                return this.Pardet_EstadoActivoField;
            }
            set {
                if ((this.Pardet_EstadoActivoField.Equals(value) != true)) {
                    this.Pardet_EstadoActivoField = value;
                    this.RaisePropertyChanged("Pardet_EstadoActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_EstadoDepreciacion {
            get {
                return this.Pardet_EstadoDepreciacionField;
            }
            set {
                if ((this.Pardet_EstadoDepreciacionField.Equals(value) != true)) {
                    this.Pardet_EstadoDepreciacionField = value;
                    this.RaisePropertyChanged("Pardet_EstadoDepreciacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Grupo {
            get {
                return this.Pardet_GrupoField;
            }
            set {
                if ((this.Pardet_GrupoField.Equals(value) != true)) {
                    this.Pardet_GrupoField = value;
                    this.RaisePropertyChanged("Pardet_Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Marca {
            get {
                return this.Pardet_MarcaField;
            }
            set {
                if ((this.Pardet_MarcaField.Equals(value) != true)) {
                    this.Pardet_MarcaField = value;
                    this.RaisePropertyChanged("Pardet_Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Tipo {
            get {
                return this.Pardet_TipoField;
            }
            set {
                if ((this.Pardet_TipoField.Equals(value) != true)) {
                    this.Pardet_TipoField = value;
                    this.RaisePropertyChanged("Pardet_Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_TipoBajaActivo {
            get {
                return this.Pardet_TipoBajaActivoField;
            }
            set {
                if ((this.Pardet_TipoBajaActivoField.Equals(value) != true)) {
                    this.Pardet_TipoBajaActivoField = value;
                    this.RaisePropertyChanged("Pardet_TipoBajaActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Ubicacion {
            get {
                return this.Pardet_UbicacionField;
            }
            set {
                if ((this.Pardet_UbicacionField.Equals(value) != true)) {
                    this.Pardet_UbicacionField = value;
                    this.RaisePropertyChanged("Pardet_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool esNuevo {
            get {
                return this.esNuevoField;
            }
            set {
                if ((this.esNuevoField.Equals(value) != true)) {
                    this.esNuevoField = value;
                    this.RaisePropertyChanged("esNuevo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Caracteristica", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Caracteristica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActCar_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaracteristicaTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_CaracteristicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_CaracteristicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool esNuevoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActCar_Descripcion {
            get {
                return this.ActCar_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActCar_DescripcionField, value) != true)) {
                    this.ActCar_DescripcionField = value;
                    this.RaisePropertyChanged("ActCar_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaracteristicaText {
            get {
                return this.CaracteristicaTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristicaTextField, value) != true)) {
                    this.CaracteristicaTextField = value;
                    this.RaisePropertyChanged("CaracteristicaText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_Caracteristica {
            get {
                return this.Parame_CaracteristicaField;
            }
            set {
                if ((this.Parame_CaracteristicaField.Equals(value) != true)) {
                    this.Parame_CaracteristicaField = value;
                    this.RaisePropertyChanged("Parame_Caracteristica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Caracteristica {
            get {
                return this.Pardet_CaracteristicaField;
            }
            set {
                if ((this.Pardet_CaracteristicaField.Equals(value) != true)) {
                    this.Pardet_CaracteristicaField = value;
                    this.RaisePropertyChanged("Pardet_Caracteristica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool esNuevo {
            get {
                return this.esNuevoField;
            }
            set {
                if ((this.esNuevoField.Equals(value) != true)) {
                    this.esNuevoField = value;
                    this.RaisePropertyChanged("esNuevo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventario", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Inventario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Invent_FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_EstadoInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_PeriodoInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_EstadoInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_PeriodoInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_UbicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Invent_Fecha {
            get {
                return this.Invent_FechaField;
            }
            set {
                if ((this.Invent_FechaField.Equals(value) != true)) {
                    this.Invent_FechaField = value;
                    this.RaisePropertyChanged("Invent_Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_EstadoInventario {
            get {
                return this.Parame_EstadoInventarioField;
            }
            set {
                if ((this.Parame_EstadoInventarioField.Equals(value) != true)) {
                    this.Parame_EstadoInventarioField = value;
                    this.RaisePropertyChanged("Parame_EstadoInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_PeriodoInventario {
            get {
                return this.Parame_PeriodoInventarioField;
            }
            set {
                if ((this.Parame_PeriodoInventarioField.Equals(value) != true)) {
                    this.Parame_PeriodoInventarioField = value;
                    this.RaisePropertyChanged("Parame_PeriodoInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_Ubicacion {
            get {
                return this.Parame_UbicacionField;
            }
            set {
                if ((this.Parame_UbicacionField.Equals(value) != true)) {
                    this.Parame_UbicacionField = value;
                    this.RaisePropertyChanged("Parame_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_EstadoInventario {
            get {
                return this.Pardet_EstadoInventarioField;
            }
            set {
                if ((this.Pardet_EstadoInventarioField.Equals(value) != true)) {
                    this.Pardet_EstadoInventarioField = value;
                    this.RaisePropertyChanged("Pardet_EstadoInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_PeriodoInventario {
            get {
                return this.Pardet_PeriodoInventarioField;
            }
            set {
                if ((this.Pardet_PeriodoInventarioField.Equals(value) != true)) {
                    this.Pardet_PeriodoInventarioField = value;
                    this.RaisePropertyChanged("Pardet_PeriodoInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Ubicacion {
            get {
                return this.Pardet_UbicacionField;
            }
            set {
                if ((this.Pardet_UbicacionField.Equals(value) != true)) {
                    this.Pardet_UbicacionField = value;
                    this.RaisePropertyChanged("Pardet_Ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Emplea_CustodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Emplea_Custodio {
            get {
                return this.Emplea_CustodioField;
            }
            set {
                if ((this.Emplea_CustodioField.Equals(value) != true)) {
                    this.Emplea_CustodioField = value;
                    this.RaisePropertyChanged("Emplea_Custodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Factura_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Factura_Codigo {
            get {
                return this.Factura_CodigoField;
            }
            set {
                if ((this.Factura_CodigoField.Equals(value) != true)) {
                    this.Factura_CodigoField = value;
                    this.RaisePropertyChanged("Factura_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Provee_CodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Provee_Codigo {
            get {
                return this.Provee_CodigoField;
            }
            set {
                if ((this.Provee_CodigoField.Equals(value) != true)) {
                    this.Provee_CodigoField = value;
                    this.RaisePropertyChanged("Provee_Codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametro", Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    [System.SerializableAttribute()]
    public partial class Parametro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Parame_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pardet_SecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parame_Codigo {
            get {
                return this.Parame_CodigoField;
            }
            set {
                if ((this.Parame_CodigoField.Equals(value) != true)) {
                    this.Parame_CodigoField = value;
                    this.RaisePropertyChanged("Parame_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pardet_Secuencia {
            get {
                return this.Pardet_SecuenciaField;
            }
            set {
                if ((this.Pardet_SecuenciaField.Equals(value) != true)) {
                    this.Pardet_SecuenciaField = value;
                    this.RaisePropertyChanged("Pardet_Secuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IActivosFijosService")]
    public interface IActivosFijosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/CargarActivo", ReplyAction="http://tempuri.org/IActivosFijosService/CargarActivoResponse")]
        WebInventario.ServiceReference1.Activo CargarActivo(string Activo_Codigo, string Serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/CargarActivo", ReplyAction="http://tempuri.org/IActivosFijosService/CargarActivoResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Activo> CargarActivoAsync(string Activo_Codigo, string Serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ActivoInventariado", ReplyAction="http://tempuri.org/IActivosFijosService/ActivoInventariadoResponse")]
        bool ActivoInventariado(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ActivoInventariado", ReplyAction="http://tempuri.org/IActivosFijosService/ActivoInventariadoResponse")]
        System.Threading.Tasks.Task<bool> ActivoInventariadoAsync(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/GuardarInventarioDet", ReplyAction="http://tempuri.org/IActivosFijosService/GuardarInventarioDetResponse")]
        string GuardarInventarioDet(string mUsuario, WebInventario.ServiceReference1.Inventario mInventario, WebInventario.ServiceReference1.Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/GuardarInventarioDet", ReplyAction="http://tempuri.org/IActivosFijosService/GuardarInventarioDetResponse")]
        System.Threading.Tasks.Task<string> GuardarInventarioDetAsync(string mUsuario, WebInventario.ServiceReference1.Inventario mInventario, WebInventario.ServiceReference1.Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaActivos", ReplyAction="http://tempuri.org/IActivosFijosService/ListaActivosResponse")]
        WebInventario.ServiceReference1.Activo[] ListaActivos(int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion, WebInventario.ServiceReference1.Inventario mInventario, bool soloInventariados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaActivos", ReplyAction="http://tempuri.org/IActivosFijosService/ListaActivosResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Activo[]> ListaActivosAsync(int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion, WebInventario.ServiceReference1.Inventario mInventario, bool soloInventariados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/IniciarSesion", ReplyAction="http://tempuri.org/IActivosFijosService/IniciarSesionResponse")]
        bool IniciarSesion(string mUsuario, string mContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/IniciarSesion", ReplyAction="http://tempuri.org/IActivosFijosService/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string mUsuario, string mContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/InventariosActivos", ReplyAction="http://tempuri.org/IActivosFijosService/InventariosActivosResponse")]
        WebInventario.ServiceReference1.Inventario[] InventariosActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/InventariosActivos", ReplyAction="http://tempuri.org/IActivosFijosService/InventariosActivosResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Inventario[]> InventariosActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaCaracteristicas", ReplyAction="http://tempuri.org/IActivosFijosService/ListaCaracteristicasResponse")]
        WebInventario.ServiceReference1.Caracteristica[] ListaCaracteristicas(int parame_tipo, int pardet_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaCaracteristicas", ReplyAction="http://tempuri.org/IActivosFijosService/ListaCaracteristicasResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Caracteristica[]> ListaCaracteristicasAsync(int parame_tipo, int pardet_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaEmpleados", ReplyAction="http://tempuri.org/IActivosFijosService/ListaEmpleadosResponse")]
        WebInventario.ServiceReference1.Empleado[] ListaEmpleados(string parcial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaEmpleados", ReplyAction="http://tempuri.org/IActivosFijosService/ListaEmpleadosResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Empleado[]> ListaEmpleadosAsync(string parcial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaFacturas", ReplyAction="http://tempuri.org/IActivosFijosService/ListaFacturasResponse")]
        WebInventario.ServiceReference1.Factura[] ListaFacturas(int _proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaFacturas", ReplyAction="http://tempuri.org/IActivosFijosService/ListaFacturasResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Factura[]> ListaFacturasAsync(int _proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaProveedores", ReplyAction="http://tempuri.org/IActivosFijosService/ListaProveedoresResponse")]
        WebInventario.ServiceReference1.Proveedor[] ListaProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ListaProveedores", ReplyAction="http://tempuri.org/IActivosFijosService/ListaProveedoresResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Proveedor[]> ListaProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ParametroList", ReplyAction="http://tempuri.org/IActivosFijosService/ParametroListResponse")]
        WebInventario.ServiceReference1.Parametro[] ParametroList(int parame_codigo, int parame_padre, int pardet_padre, string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ParametroList", ReplyAction="http://tempuri.org/IActivosFijosService/ParametroListResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Parametro[]> ParametroListAsync(int parame_codigo, int parame_padre, int pardet_padre, string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ParametroTreeList", ReplyAction="http://tempuri.org/IActivosFijosService/ParametroTreeListResponse")]
        WebInventario.ServiceReference1.Parametro[] ParametroTreeList(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivosFijosService/ParametroTreeList", ReplyAction="http://tempuri.org/IActivosFijosService/ParametroTreeListResponse")]
        System.Threading.Tasks.Task<WebInventario.ServiceReference1.Parametro[]> ParametroTreeListAsync(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActivosFijosServiceChannel : WebInventario.ServiceReference1.IActivosFijosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivosFijosServiceClient : System.ServiceModel.ClientBase<WebInventario.ServiceReference1.IActivosFijosService>, WebInventario.ServiceReference1.IActivosFijosService {
        
        public ActivosFijosServiceClient() {
        }
        
        public ActivosFijosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivosFijosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivosFijosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivosFijosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebInventario.ServiceReference1.Activo CargarActivo(string Activo_Codigo, string Serie) {
            return base.Channel.CargarActivo(Activo_Codigo, Serie);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Activo> CargarActivoAsync(string Activo_Codigo, string Serie) {
            return base.Channel.CargarActivoAsync(Activo_Codigo, Serie);
        }
        
        public bool ActivoInventariado(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario) {
            return base.Channel.ActivoInventariado(Activo_Codigo, Parame_PeriodoInventario, Pardet_PeriodoInventario);
        }
        
        public System.Threading.Tasks.Task<bool> ActivoInventariadoAsync(int Activo_Codigo, int Parame_PeriodoInventario, int Pardet_PeriodoInventario) {
            return base.Channel.ActivoInventariadoAsync(Activo_Codigo, Parame_PeriodoInventario, Pardet_PeriodoInventario);
        }
        
        public string GuardarInventarioDet(string mUsuario, WebInventario.ServiceReference1.Inventario mInventario, WebInventario.ServiceReference1.Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion) {
            return base.Channel.GuardarInventarioDet(mUsuario, mInventario, mActivo, mCustodio, mParame_Ubicacion, mPardet_Ubicacion);
        }
        
        public System.Threading.Tasks.Task<string> GuardarInventarioDetAsync(string mUsuario, WebInventario.ServiceReference1.Inventario mInventario, WebInventario.ServiceReference1.Activo mActivo, int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion) {
            return base.Channel.GuardarInventarioDetAsync(mUsuario, mInventario, mActivo, mCustodio, mParame_Ubicacion, mPardet_Ubicacion);
        }
        
        public WebInventario.ServiceReference1.Activo[] ListaActivos(int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion, WebInventario.ServiceReference1.Inventario mInventario, bool soloInventariados) {
            return base.Channel.ListaActivos(mCustodio, mParame_Ubicacion, mPardet_Ubicacion, mInventario, soloInventariados);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Activo[]> ListaActivosAsync(int mCustodio, int mParame_Ubicacion, int mPardet_Ubicacion, WebInventario.ServiceReference1.Inventario mInventario, bool soloInventariados) {
            return base.Channel.ListaActivosAsync(mCustodio, mParame_Ubicacion, mPardet_Ubicacion, mInventario, soloInventariados);
        }
        
        public bool IniciarSesion(string mUsuario, string mContrasena) {
            return base.Channel.IniciarSesion(mUsuario, mContrasena);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string mUsuario, string mContrasena) {
            return base.Channel.IniciarSesionAsync(mUsuario, mContrasena);
        }
        
        public WebInventario.ServiceReference1.Inventario[] InventariosActivos() {
            return base.Channel.InventariosActivos();
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Inventario[]> InventariosActivosAsync() {
            return base.Channel.InventariosActivosAsync();
        }
        
        public WebInventario.ServiceReference1.Caracteristica[] ListaCaracteristicas(int parame_tipo, int pardet_tipo) {
            return base.Channel.ListaCaracteristicas(parame_tipo, pardet_tipo);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Caracteristica[]> ListaCaracteristicasAsync(int parame_tipo, int pardet_tipo) {
            return base.Channel.ListaCaracteristicasAsync(parame_tipo, pardet_tipo);
        }
        
        public WebInventario.ServiceReference1.Empleado[] ListaEmpleados(string parcial) {
            return base.Channel.ListaEmpleados(parcial);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Empleado[]> ListaEmpleadosAsync(string parcial) {
            return base.Channel.ListaEmpleadosAsync(parcial);
        }
        
        public WebInventario.ServiceReference1.Factura[] ListaFacturas(int _proveedor) {
            return base.Channel.ListaFacturas(_proveedor);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Factura[]> ListaFacturasAsync(int _proveedor) {
            return base.Channel.ListaFacturasAsync(_proveedor);
        }
        
        public WebInventario.ServiceReference1.Proveedor[] ListaProveedores() {
            return base.Channel.ListaProveedores();
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Proveedor[]> ListaProveedoresAsync() {
            return base.Channel.ListaProveedoresAsync();
        }
        
        public WebInventario.ServiceReference1.Parametro[] ParametroList(int parame_codigo, int parame_padre, int pardet_padre, string filtro) {
            return base.Channel.ParametroList(parame_codigo, parame_padre, pardet_padre, filtro);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Parametro[]> ParametroListAsync(int parame_codigo, int parame_padre, int pardet_padre, string filtro) {
            return base.Channel.ParametroListAsync(parame_codigo, parame_padre, pardet_padre, filtro);
        }
        
        public WebInventario.ServiceReference1.Parametro[] ParametroTreeList(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles) {
            return base.Channel.ParametroTreeList(parame_inicio, pardet_inicio, parame_fin, solo_visibles);
        }
        
        public System.Threading.Tasks.Task<WebInventario.ServiceReference1.Parametro[]> ParametroTreeListAsync(int parame_inicio, int pardet_inicio, int parame_fin, bool solo_visibles) {
            return base.Channel.ParametroTreeListAsync(parame_inicio, pardet_inicio, parame_fin, solo_visibles);
        }
    }
}
