//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AndrodAppInventario.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IActivosFijosService", Namespace="http://tempuri.org/")]
    public partial class ActivosFijosService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CargarActivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivoInventariadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInventarioDetOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaActivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InventariosActivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaCaracteristicasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaEmpleadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaFacturasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParametroListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParametroTreeListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActivosFijosService() {
            this.Url = "http://localhost:8889/ActivosFijos.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CargarActivoCompletedEventHandler CargarActivoCompleted;
        
        /// <remarks/>
        public event ActivoInventariadoCompletedEventHandler ActivoInventariadoCompleted;
        
        /// <remarks/>
        public event GuardarInventarioDetCompletedEventHandler GuardarInventarioDetCompleted;
        
        /// <remarks/>
        public event ListaActivosCompletedEventHandler ListaActivosCompleted;
        
        /// <remarks/>
        public event IniciarSesionCompletedEventHandler IniciarSesionCompleted;
        
        /// <remarks/>
        public event InventariosActivosCompletedEventHandler InventariosActivosCompleted;
        
        /// <remarks/>
        public event ListaCaracteristicasCompletedEventHandler ListaCaracteristicasCompleted;
        
        /// <remarks/>
        public event ListaEmpleadosCompletedEventHandler ListaEmpleadosCompleted;
        
        /// <remarks/>
        public event ListaFacturasCompletedEventHandler ListaFacturasCompleted;
        
        /// <remarks/>
        public event ListaProveedoresCompletedEventHandler ListaProveedoresCompleted;
        
        /// <remarks/>
        public event ParametroListCompletedEventHandler ParametroListCompleted;
        
        /// <remarks/>
        public event ParametroTreeListCompletedEventHandler ParametroTreeListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/CargarActivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Activo CargarActivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Activo_Codigo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Serie) {
            object[] results = this.Invoke("CargarActivo", new object[] {
                        Activo_Codigo,
                        Serie});
            return ((Activo)(results[0]));
        }
        
        /// <remarks/>
        public void CargarActivoAsync(string Activo_Codigo, string Serie) {
            this.CargarActivoAsync(Activo_Codigo, Serie, null);
        }
        
        /// <remarks/>
        public void CargarActivoAsync(string Activo_Codigo, string Serie, object userState) {
            if ((this.CargarActivoOperationCompleted == null)) {
                this.CargarActivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarActivoOperationCompleted);
            }
            this.InvokeAsync("CargarActivo", new object[] {
                        Activo_Codigo,
                        Serie}, this.CargarActivoOperationCompleted, userState);
        }
        
        private void OnCargarActivoOperationCompleted(object arg) {
            if ((this.CargarActivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarActivoCompleted(this, new CargarActivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ActivoInventariado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActivoInventariado(int Activo_Codigo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Activo_CodigoSpecified, int Parame_PeriodoInventario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Parame_PeriodoInventarioSpecified, int Pardet_PeriodoInventario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Pardet_PeriodoInventarioSpecified, out bool ActivoInventariadoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ActivoInventariadoResultSpecified) {
            object[] results = this.Invoke("ActivoInventariado", new object[] {
                        Activo_Codigo,
                        Activo_CodigoSpecified,
                        Parame_PeriodoInventario,
                        Parame_PeriodoInventarioSpecified,
                        Pardet_PeriodoInventario,
                        Pardet_PeriodoInventarioSpecified});
            ActivoInventariadoResult = ((bool)(results[0]));
            ActivoInventariadoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ActivoInventariadoAsync(int Activo_Codigo, bool Activo_CodigoSpecified, int Parame_PeriodoInventario, bool Parame_PeriodoInventarioSpecified, int Pardet_PeriodoInventario, bool Pardet_PeriodoInventarioSpecified) {
            this.ActivoInventariadoAsync(Activo_Codigo, Activo_CodigoSpecified, Parame_PeriodoInventario, Parame_PeriodoInventarioSpecified, Pardet_PeriodoInventario, Pardet_PeriodoInventarioSpecified, null);
        }
        
        /// <remarks/>
        public void ActivoInventariadoAsync(int Activo_Codigo, bool Activo_CodigoSpecified, int Parame_PeriodoInventario, bool Parame_PeriodoInventarioSpecified, int Pardet_PeriodoInventario, bool Pardet_PeriodoInventarioSpecified, object userState) {
            if ((this.ActivoInventariadoOperationCompleted == null)) {
                this.ActivoInventariadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivoInventariadoOperationCompleted);
            }
            this.InvokeAsync("ActivoInventariado", new object[] {
                        Activo_Codigo,
                        Activo_CodigoSpecified,
                        Parame_PeriodoInventario,
                        Parame_PeriodoInventarioSpecified,
                        Pardet_PeriodoInventario,
                        Pardet_PeriodoInventarioSpecified}, this.ActivoInventariadoOperationCompleted, userState);
        }
        
        private void OnActivoInventariadoOperationCompleted(object arg) {
            if ((this.ActivoInventariadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivoInventariadoCompleted(this, new ActivoInventariadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/GuardarInventarioDet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GuardarInventarioDet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mUsuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Inventario mInventario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Activo mActivo, int mCustodio, [System.Xml.Serialization.XmlIgnoreAttribute()] bool mCustodioSpecified, int mParame_Ubicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool mParame_UbicacionSpecified, int mPardet_Ubicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool mPardet_UbicacionSpecified) {
            object[] results = this.Invoke("GuardarInventarioDet", new object[] {
                        mUsuario,
                        mInventario,
                        mActivo,
                        mCustodio,
                        mCustodioSpecified,
                        mParame_Ubicacion,
                        mParame_UbicacionSpecified,
                        mPardet_Ubicacion,
                        mPardet_UbicacionSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarInventarioDetAsync(string mUsuario, Inventario mInventario, Activo mActivo, int mCustodio, bool mCustodioSpecified, int mParame_Ubicacion, bool mParame_UbicacionSpecified, int mPardet_Ubicacion, bool mPardet_UbicacionSpecified) {
            this.GuardarInventarioDetAsync(mUsuario, mInventario, mActivo, mCustodio, mCustodioSpecified, mParame_Ubicacion, mParame_UbicacionSpecified, mPardet_Ubicacion, mPardet_UbicacionSpecified, null);
        }
        
        /// <remarks/>
        public void GuardarInventarioDetAsync(string mUsuario, Inventario mInventario, Activo mActivo, int mCustodio, bool mCustodioSpecified, int mParame_Ubicacion, bool mParame_UbicacionSpecified, int mPardet_Ubicacion, bool mPardet_UbicacionSpecified, object userState) {
            if ((this.GuardarInventarioDetOperationCompleted == null)) {
                this.GuardarInventarioDetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInventarioDetOperationCompleted);
            }
            this.InvokeAsync("GuardarInventarioDet", new object[] {
                        mUsuario,
                        mInventario,
                        mActivo,
                        mCustodio,
                        mCustodioSpecified,
                        mParame_Ubicacion,
                        mParame_UbicacionSpecified,
                        mPardet_Ubicacion,
                        mPardet_UbicacionSpecified}, this.GuardarInventarioDetOperationCompleted, userState);
        }
        
        private void OnGuardarInventarioDetOperationCompleted(object arg) {
            if ((this.GuardarInventarioDetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInventarioDetCompleted(this, new GuardarInventarioDetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ListaActivos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Activo[] ListaActivos(int mCustodio, [System.Xml.Serialization.XmlIgnoreAttribute()] bool mCustodioSpecified, int mParame_Ubicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool mParame_UbicacionSpecified, int mPardet_Ubicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool mPardet_UbicacionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Inventario mInventario, bool soloInventariados, [System.Xml.Serialization.XmlIgnoreAttribute()] bool soloInventariadosSpecified) {
            object[] results = this.Invoke("ListaActivos", new object[] {
                        mCustodio,
                        mCustodioSpecified,
                        mParame_Ubicacion,
                        mParame_UbicacionSpecified,
                        mPardet_Ubicacion,
                        mPardet_UbicacionSpecified,
                        mInventario,
                        soloInventariados,
                        soloInventariadosSpecified});
            return ((Activo[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaActivosAsync(int mCustodio, bool mCustodioSpecified, int mParame_Ubicacion, bool mParame_UbicacionSpecified, int mPardet_Ubicacion, bool mPardet_UbicacionSpecified, Inventario mInventario, bool soloInventariados, bool soloInventariadosSpecified) {
            this.ListaActivosAsync(mCustodio, mCustodioSpecified, mParame_Ubicacion, mParame_UbicacionSpecified, mPardet_Ubicacion, mPardet_UbicacionSpecified, mInventario, soloInventariados, soloInventariadosSpecified, null);
        }
        
        /// <remarks/>
        public void ListaActivosAsync(int mCustodio, bool mCustodioSpecified, int mParame_Ubicacion, bool mParame_UbicacionSpecified, int mPardet_Ubicacion, bool mPardet_UbicacionSpecified, Inventario mInventario, bool soloInventariados, bool soloInventariadosSpecified, object userState) {
            if ((this.ListaActivosOperationCompleted == null)) {
                this.ListaActivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaActivosOperationCompleted);
            }
            this.InvokeAsync("ListaActivos", new object[] {
                        mCustodio,
                        mCustodioSpecified,
                        mParame_Ubicacion,
                        mParame_UbicacionSpecified,
                        mPardet_Ubicacion,
                        mPardet_UbicacionSpecified,
                        mInventario,
                        soloInventariados,
                        soloInventariadosSpecified}, this.ListaActivosOperationCompleted, userState);
        }
        
        private void OnListaActivosOperationCompleted(object arg) {
            if ((this.ListaActivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaActivosCompleted(this, new ListaActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/IniciarSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IniciarSesion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mUsuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mContrasena, out bool IniciarSesionResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IniciarSesionResultSpecified) {
            object[] results = this.Invoke("IniciarSesion", new object[] {
                        mUsuario,
                        mContrasena});
            IniciarSesionResult = ((bool)(results[0]));
            IniciarSesionResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string mUsuario, string mContrasena) {
            this.IniciarSesionAsync(mUsuario, mContrasena, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string mUsuario, string mContrasena, object userState) {
            if ((this.IniciarSesionOperationCompleted == null)) {
                this.IniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionOperationCompleted);
            }
            this.InvokeAsync("IniciarSesion", new object[] {
                        mUsuario,
                        mContrasena}, this.IniciarSesionOperationCompleted, userState);
        }
        
        private void OnIniciarSesionOperationCompleted(object arg) {
            if ((this.IniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/InventariosActivos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Inventario[] InventariosActivos() {
            object[] results = this.Invoke("InventariosActivos", new object[0]);
            return ((Inventario[])(results[0]));
        }
        
        /// <remarks/>
        public void InventariosActivosAsync() {
            this.InventariosActivosAsync(null);
        }
        
        /// <remarks/>
        public void InventariosActivosAsync(object userState) {
            if ((this.InventariosActivosOperationCompleted == null)) {
                this.InventariosActivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInventariosActivosOperationCompleted);
            }
            this.InvokeAsync("InventariosActivos", new object[0], this.InventariosActivosOperationCompleted, userState);
        }
        
        private void OnInventariosActivosOperationCompleted(object arg) {
            if ((this.InventariosActivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InventariosActivosCompleted(this, new InventariosActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ListaCaracteristicas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Caracteristica[] ListaCaracteristicas(int parame_tipo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool parame_tipoSpecified, int pardet_tipo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pardet_tipoSpecified) {
            object[] results = this.Invoke("ListaCaracteristicas", new object[] {
                        parame_tipo,
                        parame_tipoSpecified,
                        pardet_tipo,
                        pardet_tipoSpecified});
            return ((Caracteristica[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaCaracteristicasAsync(int parame_tipo, bool parame_tipoSpecified, int pardet_tipo, bool pardet_tipoSpecified) {
            this.ListaCaracteristicasAsync(parame_tipo, parame_tipoSpecified, pardet_tipo, pardet_tipoSpecified, null);
        }
        
        /// <remarks/>
        public void ListaCaracteristicasAsync(int parame_tipo, bool parame_tipoSpecified, int pardet_tipo, bool pardet_tipoSpecified, object userState) {
            if ((this.ListaCaracteristicasOperationCompleted == null)) {
                this.ListaCaracteristicasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaCaracteristicasOperationCompleted);
            }
            this.InvokeAsync("ListaCaracteristicas", new object[] {
                        parame_tipo,
                        parame_tipoSpecified,
                        pardet_tipo,
                        pardet_tipoSpecified}, this.ListaCaracteristicasOperationCompleted, userState);
        }
        
        private void OnListaCaracteristicasOperationCompleted(object arg) {
            if ((this.ListaCaracteristicasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaCaracteristicasCompleted(this, new ListaCaracteristicasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ListaEmpleados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Empleado[] ListaEmpleados([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parcial) {
            object[] results = this.Invoke("ListaEmpleados", new object[] {
                        parcial});
            return ((Empleado[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaEmpleadosAsync(string parcial) {
            this.ListaEmpleadosAsync(parcial, null);
        }
        
        /// <remarks/>
        public void ListaEmpleadosAsync(string parcial, object userState) {
            if ((this.ListaEmpleadosOperationCompleted == null)) {
                this.ListaEmpleadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaEmpleadosOperationCompleted);
            }
            this.InvokeAsync("ListaEmpleados", new object[] {
                        parcial}, this.ListaEmpleadosOperationCompleted, userState);
        }
        
        private void OnListaEmpleadosOperationCompleted(object arg) {
            if ((this.ListaEmpleadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaEmpleadosCompleted(this, new ListaEmpleadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ListaFacturas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Factura[] ListaFacturas(int _proveedor, [System.Xml.Serialization.XmlIgnoreAttribute()] bool _proveedorSpecified) {
            object[] results = this.Invoke("ListaFacturas", new object[] {
                        _proveedor,
                        _proveedorSpecified});
            return ((Factura[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaFacturasAsync(int _proveedor, bool _proveedorSpecified) {
            this.ListaFacturasAsync(_proveedor, _proveedorSpecified, null);
        }
        
        /// <remarks/>
        public void ListaFacturasAsync(int _proveedor, bool _proveedorSpecified, object userState) {
            if ((this.ListaFacturasOperationCompleted == null)) {
                this.ListaFacturasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaFacturasOperationCompleted);
            }
            this.InvokeAsync("ListaFacturas", new object[] {
                        _proveedor,
                        _proveedorSpecified}, this.ListaFacturasOperationCompleted, userState);
        }
        
        private void OnListaFacturasOperationCompleted(object arg) {
            if ((this.ListaFacturasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaFacturasCompleted(this, new ListaFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ListaProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Proveedor[] ListaProveedores() {
            object[] results = this.Invoke("ListaProveedores", new object[0]);
            return ((Proveedor[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaProveedoresAsync() {
            this.ListaProveedoresAsync(null);
        }
        
        /// <remarks/>
        public void ListaProveedoresAsync(object userState) {
            if ((this.ListaProveedoresOperationCompleted == null)) {
                this.ListaProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaProveedoresOperationCompleted);
            }
            this.InvokeAsync("ListaProveedores", new object[0], this.ListaProveedoresOperationCompleted, userState);
        }
        
        private void OnListaProveedoresOperationCompleted(object arg) {
            if ((this.ListaProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaProveedoresCompleted(this, new ListaProveedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ParametroList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Parametro[] ParametroList(int parame_codigo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool parame_codigoSpecified, int parame_padre, [System.Xml.Serialization.XmlIgnoreAttribute()] bool parame_padreSpecified, int pardet_padre, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pardet_padreSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string filtro) {
            object[] results = this.Invoke("ParametroList", new object[] {
                        parame_codigo,
                        parame_codigoSpecified,
                        parame_padre,
                        parame_padreSpecified,
                        pardet_padre,
                        pardet_padreSpecified,
                        filtro});
            return ((Parametro[])(results[0]));
        }
        
        /// <remarks/>
        public void ParametroListAsync(int parame_codigo, bool parame_codigoSpecified, int parame_padre, bool parame_padreSpecified, int pardet_padre, bool pardet_padreSpecified, string filtro) {
            this.ParametroListAsync(parame_codigo, parame_codigoSpecified, parame_padre, parame_padreSpecified, pardet_padre, pardet_padreSpecified, filtro, null);
        }
        
        /// <remarks/>
        public void ParametroListAsync(int parame_codigo, bool parame_codigoSpecified, int parame_padre, bool parame_padreSpecified, int pardet_padre, bool pardet_padreSpecified, string filtro, object userState) {
            if ((this.ParametroListOperationCompleted == null)) {
                this.ParametroListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParametroListOperationCompleted);
            }
            this.InvokeAsync("ParametroList", new object[] {
                        parame_codigo,
                        parame_codigoSpecified,
                        parame_padre,
                        parame_padreSpecified,
                        pardet_padre,
                        pardet_padreSpecified,
                        filtro}, this.ParametroListOperationCompleted, userState);
        }
        
        private void OnParametroListOperationCompleted(object arg) {
            if ((this.ParametroListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParametroListCompleted(this, new ParametroListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IActivosFijosService/ParametroTreeList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
        public Parametro[] ParametroTreeList(int parame_inicio, [System.Xml.Serialization.XmlIgnoreAttribute()] bool parame_inicioSpecified, int pardet_inicio, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pardet_inicioSpecified, int parame_fin, [System.Xml.Serialization.XmlIgnoreAttribute()] bool parame_finSpecified, bool solo_visibles, [System.Xml.Serialization.XmlIgnoreAttribute()] bool solo_visiblesSpecified) {
            object[] results = this.Invoke("ParametroTreeList", new object[] {
                        parame_inicio,
                        parame_inicioSpecified,
                        pardet_inicio,
                        pardet_inicioSpecified,
                        parame_fin,
                        parame_finSpecified,
                        solo_visibles,
                        solo_visiblesSpecified});
            return ((Parametro[])(results[0]));
        }
        
        /// <remarks/>
        public void ParametroTreeListAsync(int parame_inicio, bool parame_inicioSpecified, int pardet_inicio, bool pardet_inicioSpecified, int parame_fin, bool parame_finSpecified, bool solo_visibles, bool solo_visiblesSpecified) {
            this.ParametroTreeListAsync(parame_inicio, parame_inicioSpecified, pardet_inicio, pardet_inicioSpecified, parame_fin, parame_finSpecified, solo_visibles, solo_visiblesSpecified, null);
        }
        
        /// <remarks/>
        public void ParametroTreeListAsync(int parame_inicio, bool parame_inicioSpecified, int pardet_inicio, bool pardet_inicioSpecified, int parame_fin, bool parame_finSpecified, bool solo_visibles, bool solo_visiblesSpecified, object userState) {
            if ((this.ParametroTreeListOperationCompleted == null)) {
                this.ParametroTreeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParametroTreeListOperationCompleted);
            }
            this.InvokeAsync("ParametroTreeList", new object[] {
                        parame_inicio,
                        parame_inicioSpecified,
                        pardet_inicio,
                        pardet_inicioSpecified,
                        parame_fin,
                        parame_finSpecified,
                        solo_visibles,
                        solo_visiblesSpecified}, this.ParametroTreeListOperationCompleted, userState);
        }
        
        private void OnParametroTreeListOperationCompleted(object arg) {
            if ((this.ParametroTreeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParametroTreeListCompleted(this, new ParametroTreeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Activo {
        
        private int activo_CodigoField;
        
        private bool activo_CodigoFieldSpecified;
        
        private string activo_CodigoAuxField;
        
        private string activo_CodigoBarraField;
        
        private string activo_DescripcionField;
        
        private System.DateTime activo_FechaBajaField;
        
        private bool activo_FechaBajaFieldSpecified;
        
        private System.DateTime activo_FechaCompraField;
        
        private bool activo_FechaCompraFieldSpecified;
        
        private System.DateTime activo_FechaIngresoField;
        
        private bool activo_FechaIngresoFieldSpecified;
        
        private System.DateTime activo_FechaUsoField;
        
        private bool activo_FechaUsoFieldSpecified;
        
        private string activo_ModeloField;
        
        private string activo_ObservacionField;
        
        private string activo_ResponsableMantenimientoField;
        
        private string activo_SerieField;
        
        private Caracteristica[] caracteristicasField;
        
        private int entida_CustodioField;
        
        private bool entida_CustodioFieldSpecified;
        
        private int entida_ProveedorField;
        
        private bool entida_ProveedorFieldSpecified;
        
        private int factura_CodigoField;
        
        private bool factura_CodigoFieldSpecified;
        
        private int parame_CentroCostoField;
        
        private bool parame_CentroCostoFieldSpecified;
        
        private int parame_ClaseActivoField;
        
        private bool parame_ClaseActivoFieldSpecified;
        
        private int parame_EstadoActivoField;
        
        private bool parame_EstadoActivoFieldSpecified;
        
        private int parame_EstadoDepreciacionField;
        
        private bool parame_EstadoDepreciacionFieldSpecified;
        
        private int parame_MarcaField;
        
        private bool parame_MarcaFieldSpecified;
        
        private int parame_TipoBajaActivoField;
        
        private bool parame_TipoBajaActivoFieldSpecified;
        
        private int pardet_CentroCostoField;
        
        private bool pardet_CentroCostoFieldSpecified;
        
        private int pardet_ClaseActivoField;
        
        private bool pardet_ClaseActivoFieldSpecified;
        
        private int pardet_EstadoActivoField;
        
        private bool pardet_EstadoActivoFieldSpecified;
        
        private int pardet_EstadoDepreciacionField;
        
        private bool pardet_EstadoDepreciacionFieldSpecified;
        
        private int pardet_GrupoField;
        
        private bool pardet_GrupoFieldSpecified;
        
        private int pardet_MarcaField;
        
        private bool pardet_MarcaFieldSpecified;
        
        private int pardet_TipoField;
        
        private bool pardet_TipoFieldSpecified;
        
        private int pardet_TipoBajaActivoField;
        
        private bool pardet_TipoBajaActivoFieldSpecified;
        
        private int pardet_UbicacionField;
        
        private bool pardet_UbicacionFieldSpecified;
        
        private bool esNuevoField;
        
        private bool esNuevoFieldSpecified;
        
        /// <remarks/>
        public int Activo_Codigo {
            get {
                return this.activo_CodigoField;
            }
            set {
                this.activo_CodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Activo_CodigoSpecified {
            get {
                return this.activo_CodigoFieldSpecified;
            }
            set {
                this.activo_CodigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_CodigoAux {
            get {
                return this.activo_CodigoAuxField;
            }
            set {
                this.activo_CodigoAuxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_CodigoBarra {
            get {
                return this.activo_CodigoBarraField;
            }
            set {
                this.activo_CodigoBarraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_Descripcion {
            get {
                return this.activo_DescripcionField;
            }
            set {
                this.activo_DescripcionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Activo_FechaBaja {
            get {
                return this.activo_FechaBajaField;
            }
            set {
                this.activo_FechaBajaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Activo_FechaBajaSpecified {
            get {
                return this.activo_FechaBajaFieldSpecified;
            }
            set {
                this.activo_FechaBajaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Activo_FechaCompra {
            get {
                return this.activo_FechaCompraField;
            }
            set {
                this.activo_FechaCompraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Activo_FechaCompraSpecified {
            get {
                return this.activo_FechaCompraFieldSpecified;
            }
            set {
                this.activo_FechaCompraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Activo_FechaIngreso {
            get {
                return this.activo_FechaIngresoField;
            }
            set {
                this.activo_FechaIngresoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Activo_FechaIngresoSpecified {
            get {
                return this.activo_FechaIngresoFieldSpecified;
            }
            set {
                this.activo_FechaIngresoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Activo_FechaUso {
            get {
                return this.activo_FechaUsoField;
            }
            set {
                this.activo_FechaUsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Activo_FechaUsoSpecified {
            get {
                return this.activo_FechaUsoFieldSpecified;
            }
            set {
                this.activo_FechaUsoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_Modelo {
            get {
                return this.activo_ModeloField;
            }
            set {
                this.activo_ModeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_Observacion {
            get {
                return this.activo_ObservacionField;
            }
            set {
                this.activo_ObservacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_ResponsableMantenimiento {
            get {
                return this.activo_ResponsableMantenimientoField;
            }
            set {
                this.activo_ResponsableMantenimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Activo_Serie {
            get {
                return this.activo_SerieField;
            }
            set {
                this.activo_SerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Caracteristica[] Caracteristicas {
            get {
                return this.caracteristicasField;
            }
            set {
                this.caracteristicasField = value;
            }
        }
        
        /// <remarks/>
        public int Entida_Custodio {
            get {
                return this.entida_CustodioField;
            }
            set {
                this.entida_CustodioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entida_CustodioSpecified {
            get {
                return this.entida_CustodioFieldSpecified;
            }
            set {
                this.entida_CustodioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Entida_Proveedor {
            get {
                return this.entida_ProveedorField;
            }
            set {
                this.entida_ProveedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entida_ProveedorSpecified {
            get {
                return this.entida_ProveedorFieldSpecified;
            }
            set {
                this.entida_ProveedorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Factura_Codigo {
            get {
                return this.factura_CodigoField;
            }
            set {
                this.factura_CodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Factura_CodigoSpecified {
            get {
                return this.factura_CodigoFieldSpecified;
            }
            set {
                this.factura_CodigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_CentroCosto {
            get {
                return this.parame_CentroCostoField;
            }
            set {
                this.parame_CentroCostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_CentroCostoSpecified {
            get {
                return this.parame_CentroCostoFieldSpecified;
            }
            set {
                this.parame_CentroCostoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_ClaseActivo {
            get {
                return this.parame_ClaseActivoField;
            }
            set {
                this.parame_ClaseActivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_ClaseActivoSpecified {
            get {
                return this.parame_ClaseActivoFieldSpecified;
            }
            set {
                this.parame_ClaseActivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_EstadoActivo {
            get {
                return this.parame_EstadoActivoField;
            }
            set {
                this.parame_EstadoActivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_EstadoActivoSpecified {
            get {
                return this.parame_EstadoActivoFieldSpecified;
            }
            set {
                this.parame_EstadoActivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_EstadoDepreciacion {
            get {
                return this.parame_EstadoDepreciacionField;
            }
            set {
                this.parame_EstadoDepreciacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_EstadoDepreciacionSpecified {
            get {
                return this.parame_EstadoDepreciacionFieldSpecified;
            }
            set {
                this.parame_EstadoDepreciacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_Marca {
            get {
                return this.parame_MarcaField;
            }
            set {
                this.parame_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_MarcaSpecified {
            get {
                return this.parame_MarcaFieldSpecified;
            }
            set {
                this.parame_MarcaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_TipoBajaActivo {
            get {
                return this.parame_TipoBajaActivoField;
            }
            set {
                this.parame_TipoBajaActivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_TipoBajaActivoSpecified {
            get {
                return this.parame_TipoBajaActivoFieldSpecified;
            }
            set {
                this.parame_TipoBajaActivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_CentroCosto {
            get {
                return this.pardet_CentroCostoField;
            }
            set {
                this.pardet_CentroCostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_CentroCostoSpecified {
            get {
                return this.pardet_CentroCostoFieldSpecified;
            }
            set {
                this.pardet_CentroCostoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_ClaseActivo {
            get {
                return this.pardet_ClaseActivoField;
            }
            set {
                this.pardet_ClaseActivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_ClaseActivoSpecified {
            get {
                return this.pardet_ClaseActivoFieldSpecified;
            }
            set {
                this.pardet_ClaseActivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_EstadoActivo {
            get {
                return this.pardet_EstadoActivoField;
            }
            set {
                this.pardet_EstadoActivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_EstadoActivoSpecified {
            get {
                return this.pardet_EstadoActivoFieldSpecified;
            }
            set {
                this.pardet_EstadoActivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_EstadoDepreciacion {
            get {
                return this.pardet_EstadoDepreciacionField;
            }
            set {
                this.pardet_EstadoDepreciacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_EstadoDepreciacionSpecified {
            get {
                return this.pardet_EstadoDepreciacionFieldSpecified;
            }
            set {
                this.pardet_EstadoDepreciacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Grupo {
            get {
                return this.pardet_GrupoField;
            }
            set {
                this.pardet_GrupoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_GrupoSpecified {
            get {
                return this.pardet_GrupoFieldSpecified;
            }
            set {
                this.pardet_GrupoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Marca {
            get {
                return this.pardet_MarcaField;
            }
            set {
                this.pardet_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_MarcaSpecified {
            get {
                return this.pardet_MarcaFieldSpecified;
            }
            set {
                this.pardet_MarcaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Tipo {
            get {
                return this.pardet_TipoField;
            }
            set {
                this.pardet_TipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_TipoSpecified {
            get {
                return this.pardet_TipoFieldSpecified;
            }
            set {
                this.pardet_TipoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_TipoBajaActivo {
            get {
                return this.pardet_TipoBajaActivoField;
            }
            set {
                this.pardet_TipoBajaActivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_TipoBajaActivoSpecified {
            get {
                return this.pardet_TipoBajaActivoFieldSpecified;
            }
            set {
                this.pardet_TipoBajaActivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Ubicacion {
            get {
                return this.pardet_UbicacionField;
            }
            set {
                this.pardet_UbicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_UbicacionSpecified {
            get {
                return this.pardet_UbicacionFieldSpecified;
            }
            set {
                this.pardet_UbicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool esNuevo {
            get {
                return this.esNuevoField;
            }
            set {
                this.esNuevoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esNuevoSpecified {
            get {
                return this.esNuevoFieldSpecified;
            }
            set {
                this.esNuevoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Caracteristica {
        
        private string actCar_DescripcionField;
        
        private string caracteristicaTextField;
        
        private int parame_CaracteristicaField;
        
        private bool parame_CaracteristicaFieldSpecified;
        
        private int pardet_CaracteristicaField;
        
        private bool pardet_CaracteristicaFieldSpecified;
        
        private bool esNuevoField;
        
        private bool esNuevoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActCar_Descripcion {
            get {
                return this.actCar_DescripcionField;
            }
            set {
                this.actCar_DescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CaracteristicaText {
            get {
                return this.caracteristicaTextField;
            }
            set {
                this.caracteristicaTextField = value;
            }
        }
        
        /// <remarks/>
        public int Parame_Caracteristica {
            get {
                return this.parame_CaracteristicaField;
            }
            set {
                this.parame_CaracteristicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_CaracteristicaSpecified {
            get {
                return this.parame_CaracteristicaFieldSpecified;
            }
            set {
                this.parame_CaracteristicaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Caracteristica {
            get {
                return this.pardet_CaracteristicaField;
            }
            set {
                this.pardet_CaracteristicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_CaracteristicaSpecified {
            get {
                return this.pardet_CaracteristicaFieldSpecified;
            }
            set {
                this.pardet_CaracteristicaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool esNuevo {
            get {
                return this.esNuevoField;
            }
            set {
                this.esNuevoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esNuevoSpecified {
            get {
                return this.esNuevoFieldSpecified;
            }
            set {
                this.esNuevoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Parametro {
        
        private string descripcionField;
        
        private int parame_CodigoField;
        
        private bool parame_CodigoFieldSpecified;
        
        private int pardet_SecuenciaField;
        
        private bool pardet_SecuenciaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public int Parame_Codigo {
            get {
                return this.parame_CodigoField;
            }
            set {
                this.parame_CodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_CodigoSpecified {
            get {
                return this.parame_CodigoFieldSpecified;
            }
            set {
                this.parame_CodigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Secuencia {
            get {
                return this.pardet_SecuenciaField;
            }
            set {
                this.pardet_SecuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_SecuenciaSpecified {
            get {
                return this.pardet_SecuenciaFieldSpecified;
            }
            set {
                this.pardet_SecuenciaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Proveedor {
        
        private string nombreCompletoField;
        
        private int provee_CodigoField;
        
        private bool provee_CodigoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <remarks/>
        public int Provee_Codigo {
            get {
                return this.provee_CodigoField;
            }
            set {
                this.provee_CodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Provee_CodigoSpecified {
            get {
                return this.provee_CodigoFieldSpecified;
            }
            set {
                this.provee_CodigoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Factura {
        
        private int factura_CodigoField;
        
        private bool factura_CodigoFieldSpecified;
        
        private string proveedorField;
        
        /// <remarks/>
        public int Factura_Codigo {
            get {
                return this.factura_CodigoField;
            }
            set {
                this.factura_CodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Factura_CodigoSpecified {
            get {
                return this.factura_CodigoFieldSpecified;
            }
            set {
                this.factura_CodigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Proveedor {
            get {
                return this.proveedorField;
            }
            set {
                this.proveedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Empleado {
        
        private int emplea_CustodioField;
        
        private bool emplea_CustodioFieldSpecified;
        
        private string nombreCompletoField;
        
        /// <remarks/>
        public int Emplea_Custodio {
            get {
                return this.emplea_CustodioField;
            }
            set {
                this.emplea_CustodioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Emplea_CustodioSpecified {
            get {
                return this.emplea_CustodioFieldSpecified;
            }
            set {
                this.emplea_CustodioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ActivosFijosServices")]
    public partial class Inventario {
        
        private string descripcionField;
        
        private System.DateTime invent_FechaField;
        
        private bool invent_FechaFieldSpecified;
        
        private int parame_EstadoInventarioField;
        
        private bool parame_EstadoInventarioFieldSpecified;
        
        private int parame_PeriodoInventarioField;
        
        private bool parame_PeriodoInventarioFieldSpecified;
        
        private int parame_UbicacionField;
        
        private bool parame_UbicacionFieldSpecified;
        
        private int pardet_EstadoInventarioField;
        
        private bool pardet_EstadoInventarioFieldSpecified;
        
        private int pardet_PeriodoInventarioField;
        
        private bool pardet_PeriodoInventarioFieldSpecified;
        
        private int pardet_UbicacionField;
        
        private bool pardet_UbicacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Invent_Fecha {
            get {
                return this.invent_FechaField;
            }
            set {
                this.invent_FechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invent_FechaSpecified {
            get {
                return this.invent_FechaFieldSpecified;
            }
            set {
                this.invent_FechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_EstadoInventario {
            get {
                return this.parame_EstadoInventarioField;
            }
            set {
                this.parame_EstadoInventarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_EstadoInventarioSpecified {
            get {
                return this.parame_EstadoInventarioFieldSpecified;
            }
            set {
                this.parame_EstadoInventarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_PeriodoInventario {
            get {
                return this.parame_PeriodoInventarioField;
            }
            set {
                this.parame_PeriodoInventarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_PeriodoInventarioSpecified {
            get {
                return this.parame_PeriodoInventarioFieldSpecified;
            }
            set {
                this.parame_PeriodoInventarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Parame_Ubicacion {
            get {
                return this.parame_UbicacionField;
            }
            set {
                this.parame_UbicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Parame_UbicacionSpecified {
            get {
                return this.parame_UbicacionFieldSpecified;
            }
            set {
                this.parame_UbicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_EstadoInventario {
            get {
                return this.pardet_EstadoInventarioField;
            }
            set {
                this.pardet_EstadoInventarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_EstadoInventarioSpecified {
            get {
                return this.pardet_EstadoInventarioFieldSpecified;
            }
            set {
                this.pardet_EstadoInventarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_PeriodoInventario {
            get {
                return this.pardet_PeriodoInventarioField;
            }
            set {
                this.pardet_PeriodoInventarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_PeriodoInventarioSpecified {
            get {
                return this.pardet_PeriodoInventarioFieldSpecified;
            }
            set {
                this.pardet_PeriodoInventarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Pardet_Ubicacion {
            get {
                return this.pardet_UbicacionField;
            }
            set {
                this.pardet_UbicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pardet_UbicacionSpecified {
            get {
                return this.pardet_UbicacionFieldSpecified;
            }
            set {
                this.pardet_UbicacionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CargarActivoCompletedEventHandler(object sender, CargarActivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarActivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarActivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Activo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Activo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ActivoInventariadoCompletedEventHandler(object sender, ActivoInventariadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivoInventariadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivoInventariadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ActivoInventariadoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ActivoInventariadoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GuardarInventarioDetCompletedEventHandler(object sender, GuardarInventarioDetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarInventarioDetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarInventarioDetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListaActivosCompletedEventHandler(object sender, ListaActivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaActivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaActivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Activo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Activo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void IniciarSesionCompletedEventHandler(object sender, IniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IniciarSesionResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IniciarSesionResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InventariosActivosCompletedEventHandler(object sender, InventariosActivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InventariosActivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InventariosActivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inventario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inventario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListaCaracteristicasCompletedEventHandler(object sender, ListaCaracteristicasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaCaracteristicasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaCaracteristicasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Caracteristica[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Caracteristica[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListaEmpleadosCompletedEventHandler(object sender, ListaEmpleadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListaFacturasCompletedEventHandler(object sender, ListaFacturasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaFacturasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaFacturasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Factura[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Factura[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListaProveedoresCompletedEventHandler(object sender, ListaProveedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaProveedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaProveedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proveedor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proveedor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ParametroListCompletedEventHandler(object sender, ParametroListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametroListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParametroListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parametro[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parametro[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ParametroTreeListCompletedEventHandler(object sender, ParametroTreeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametroTreeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParametroTreeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parametro[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parametro[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591